### ISSUE TITLE
seed parameter should be of type Int32

### ISSUE THREAD

**Issue by gapato** [fcdimitr/LFRBenchmarkGraphs.jl#7]
The `seed` parameter of the function `lancichinetti_fortunato_radicchi!` is currently of type `Integer`. It should be of type `Int32`.

    julia> lancichinetti_fortunato_radicchi(50, 4, 8; seed=rand(Int64))
    
    ERROR: InexactError: trunc(Int32, 3790894905704071339)
    Stacktrace:
      [1] throw_inexacterror(f::Symbol, ::Type{Int32}, val::Int64)
      ...

But:

    julia> lancichinetti_fortunato_radicchi(50, 4, 8; seed=rand(Int32))
    
    (Graphs.SimpleGraphs.SimpleGraph{Int64}(...)

**Comment by fcdimitr** [comment]
I think the current behavior is the intended one. If the seed is defined as type `Int32`, then the following:

```julia
lancichinetti_fortunato_radicchi(50, 4, 8; seed=0)
```

throws an error
```
ERROR: TypeError: in keyword argument seed, expected Int32, got a value of type Int64
```

and the user must always specify
```julia
lancichinetti_fortunato_radicchi(50, 4, 8; seed=Int32(0) )
```

The way it works now is if the input can be translated to `Int32`, it will. Otherwise, it will throw an error (as in your example, when the range is outside the `Int32` limits).


So, if you want a random seed, use `rand(Int32)` instead of `rand(Int64)` as input, as in your workaround.

Does this make sense? Thank you!

**Comment by gapato** [comment]
I see, my example is a conversion error, not a type error. The current behaviour is sensible since the default integer type is Int64.
